query GetPdfs($page: Int!, $limit: Int!, $filter: PdfFilterDto) {
  pdfs(page: $page, limit: $limit, filter: $filter) {
    docs {
      _id
      url
      title
      createdAt
      updatedAt
    }
    totalDocs
    totalPages
    prevPage
    page
    nextPage
    limit
    hasNextPage
    hasPrevPage
  }
}
