query gameHistoryById($input: String!) {
  gameHistoryById(input: $input) {
    ... on SinglePlayerGame {
      answers {
        timeTaken
        timeAvailable
        status
        selectedOption
        questionId
      }
      categoryId {
        name
      }
      _id
      endedAt
      mode
      score
      startedAt
      status
      totalSkipped
      totalIncorrect
      totalCorrect
      totalTimeAvailable
      totalTimeTaken
      questions {
        time
        questionText
        options
        answer
      }
    }
  }
}
